# Generated by Django 6.0.3 on 2026-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alkewallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(default='correo@banco.com', max_length=254),
        ),
    ]
